name: royal_canary_farm_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  date_format: ^2.0.7
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: 4.6.6
  get_cli: 1.8.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
  intl: 0.18.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
